# -*- coding: utf-8 -*-
"""Stack Overflow Survey Analysis | Grouping, Aggregation & Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YGgosTvD5whlqU_LGLA29XOWkN0IkU1

# Data Analysis Internship Task 4

# Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load Dataset"""

df=pd.read_csv("/content/Pokemon.csv")

df.head()

df.info()

df.dropna()

print(df.columns)

"""# Data Cleaning"""

df['Type 2'] = df['Type 2'].fillna("None")
df.isnull().sum()

"""# Grouping Data

# Grouping & Count by Category (Type 1)
"""

count_type1 = df.groupby('Type 1')['Name'].count()
print(count_type1)

"""# Total  Another Category (Generation)"""

total_by_gen = df.groupby('Generation')[['Total', 'HP', 'Attack', 'Defense',
                                         'Sp. Atk', 'Sp. Def', 'Speed']].sum()
print(total_by_gen)

"""# Group by Multiple Categories"""

grouped = df.groupby(['Type 1','Legendary'])[['Total','HP','Attack']].mean()
print(grouped.head())

"""# Average Pokémon Stats by Primary Type (Type 1)"""

avg_stats_type1 = df.groupby('Type 1').mean(numeric_only=True)
print(avg_stats_type1.head())

"""# Average Stats by Type 1"""

avg_stats_type1.to_csv("avg_stats_by_type1.csv")
print(avg_stats_type1.head())

"""# Aggregation with Multiple Functions by Pokémon Primary Type (Type 1)"""

agg_stats = df.groupby('Type 1').agg({
    'HP': ['mean', 'max', 'min'],
    'Attack': ['mean', 'sum'],
    'Defense': 'mean',
    'Speed': ['mean', 'max']
})
print(agg_stats.head())

"""# Export Aggregated Results to CSV"""

agg_stats.to_csv("final_aggregated_stats.csv")
print(agg_stats.head())

"""# "After grouping the data, I visualized the distribution of Pokémon by their primary type using a bar chart."
"""

count_type1.sort_values().plot.barh(figsize=(6,6), color="green",
    title="Number of Pokémon by Primary Type")
plt.xlabel("Count")
plt.ylabel("Type 1")
plt.show()

"""# Pokémon Distribution by Primary Type (Pie Chart)"""

count_type1.plot.pie(figsize=(5,5), ylabel="")
plt.title("Pokémon Distribution by Primary Type")
plt.show()